### ISSUE TITLE
Make client compatible with both 2.4 and 2.5 of playframework

### ISSUE THREAD

**Issue by joelsonoda** [scamandrill/scamandrill#22]
@graingert, perhaps we should release two separate versions, one compiled for play 2.4 and one compiled for play 2.5 (we could even borrow those major numbers for the two versions).

Also, since we're using play as our only dependency now, perhaps we should rename the artifacts to play-mandrill like

```"io.github.scamandrill" %% play-mandrill % "2.4.x", "io.github.scamandrill" %% play-mandrill % "2.5.x"```

Thoughts?

**Comment by graingert** [comment]
Yeah seems like a plan. Is this something we can do with macros to avoid
having two codebases?

**Comment by joelsonoda** [comment]
I think we could probably just run 2.4 as a branch off of master. The only
two things that would be different would be build.sbt and the class
currently called Scamandrill. If we moved the client-building logic out of
Scamandrill, the only place where the two branches would differ would be on
build.sbt. As such, it shouldn't be much effort to merge from master into
the 2.4 branch (or merge pull requests into both branches).

**Comment by joelsonoda** [comment]
Is it ok if I create a 2.4.x branch from master?

**Comment by joelsonoda** [comment]
Branches exist for both play 2.4 and play 2.5, so I'm gong to close this issue.
